site_name: 代码札记
site_description: 札记 
site_author: cunfus
site_url: https://cunfus.github.io/Coding-Journal/

# refer https://mkdoc-material.llango.com/customization/
#       https://github.com/squidfunk/mkdocs-material/tree/master/material/templates/partials
theme:
  name: material
  language: zh
  custom_dir: overrides
  favicon: asserts/images/code-solid.svg
  palette:
    - accent: deep orange
    - scheme: default

  font:  
    text: 'LXGW WenKai Screen'
    code: 'Fira Code' 
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate

extra_css:
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.7.0/style.css
  - stylesheets/extra.css
extra_javascript:
  - javascripts/english.js

markdown_extensions:
  ### refer from https://shafish.cn/blog/mkdocs
  - abbr            
  - tables
  - admonition           
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:  
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true


nav:
  - 首页: 
    - index.md
    - tech-view.md

  - 编程语言:
    - codelang/index.md
    - Lisp:
      - codelang/sicp/index.md
      - codelang/sicp/sicp-1.1.md
      - codelang/sicp/sicp-1.2.md
    - Python: 
      - codelang/python/index.md
    - Go:
      - codelang/go/index.md
      - codelang/go/1.md
      - codelang/go/2.md
      - codelang/go/3.md
      - codelang/go/4.md
      - codelang/go/5.md
      - codelang/go/6.md
      - codelang/go/7.md
    - JS:
      - codelang/js/index.md
    - C#:
      - codelang/c#/index.md
    - C:
      - codelang/c/index.md
      - codelang/c/1.md
      - codelang/c/2.md
      - codelang/c/3.md
      - codelang/c/4.md
      - codelang/c/5.md
      - codelang/c/6.md
      - 标准库:
        - codelang/c/stl/index.md
        - codelang/c/stl/cpy.md
      - codelang/c/omp.md
    - 语言特性:
      - codelang/lang-feat/index.md
      - codelang/lang-feat/oo.md
    - 设计模式:
      - codelang/patterns/index.md
  
  
  - 工具集:
    - tool/index.md
